### ISSUE TITLE
NuGet package availability

### ISSUE THREAD

**Issue by ScottyPcGuy-03** [OpenMacroBoard/OpenMacroBoard.ExampleCollection#1]
Do you plan to provide NuGet packages for this example collection? 

I am unable to use the sample source code in Visual Studio because the references to the dependencies are all relative, and I can't seem to get a working dependency folder structure. I've attempted to modify the relative references to point to the proper solutions, but Visual Studio ignores them for some reason. I'm sure there's something else at play here but a NuGet package would make using the examples much easier. :)

**Comment by wischi-chr** [comment]
I don't think providing packages for the examples on nuget would be the way to go, one should be able to change stuff in the example projects and experiment with it, which would be pretty hard if they are distributed with nuget packages because you wouldn't be able to edit the source and try things.

I updated the references of the example projects. They now use the nuget packages (instead of a relative non-existing SDK project) and should work right out of the box.

Please let me know if that works for you. Thx.
